variables:
  DRIVER_VERSION: "440.64.00"
  GIT_SSL_NO_VERIFY: "true"

  DOCKER_HOST: tcp://docker:2375/

image: ${CI_REGISTRY_IMAGE}/builder:latest

services:
  - docker:stable-dind

stages:
  - syntax-check
  - docker-images
  - build

shellcheck:
  stage: syntax-check
  image:
    name: koalaman/shellcheck-alpine
  services: []
  before_script: []
  script:
    - shellcheck --version
    - shellcheck --external-sources ci/run.sh
  except:
    - schedules

builder:
  before_script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
  stage: docker-images
  image: docker:stable
  script:
    - docker pull ${CI_REGISTRY_IMAGE}/builder || true
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/builder ci/
    - docker push ${CI_REGISTRY_IMAGE}/builder
  except:
    - schedules

build:
  stage: build
  variables:
    AWS_DEFAULT_REGION: us-east-1

    SSH_HOST_KEY_PATH: ssh_host_ed25519_key
    SSH_HOST_KEY_PUB_PATH: ssh_host_ed25519_key.pub
  script:
    - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_TOKEN}"

    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | ssh-add - &> /dev/null
    - mkdir -p ${HOME}/.ssh
    - chmod 700 ${HOME}/.ssh
    - ssh-add -L > ${HOME}/.ssh/id_rsa.pub

    - cd ./ci
    - terraform init -input=false
    - export CI_COMMIT_TAG="$(git describe --abbrev=0 --tags)"
    - ./run.sh
  after_script:
    - rm -rf ${HOME}/.ssh
    - rm -rf ${SSH_HOST_KEY_PATH}
    - rm -rf ${SSH_HOST_KEY_PUB_PATH}
  only:
    - master
