variables:
  DRIVER_VERSION: "396.37"
  GIT_SSL_NO_VERIFY: "true"

  DOCKER_HOST: tcp://docker:2375/

image: ${CI_REGISTRY_IMAGE}/builder:latest

services:
  - docker:stable-dind

stages:
  - syntax-check
  - docker-images
  - build

before_script:
  - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"

shellcheck:
  stage: syntax-check
  image:
    name: koalaman/shellcheck-alpine
  services: []
  before_script: []
  script:
    - shellcheck --version
    - shellcheck --external-sources run.sh
  except:
    - schedules

builder:
  stage: docker-images
  image: docker:stable
  script:
    - docker pull ${CI_REGISTRY_IMAGE}/builder || true
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/builder .
    - docker push ${CI_REGISTRY_IMAGE}/builder
  except:
    - schedules

build:
  stage: build
  variables:
    AWS_DEFAULT_REGION: us-east-1

    SSH_HOST_KEY_PATH: ssh_host_ed25519_key
    SSH_HOST_KEY_PUB_PATH: ssh_host_ed25519_key.pub

  script:
    - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_PASSWORD}"

    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | ssh-add - &> /dev/null
    - mkdir -p ${HOME}/.ssh
    - chmod 700 ${HOME}/.ssh
    - ssh-add -L > ${HOME}/.ssh/id_rsa.pub

    - echo "${SSH_HOST_KEY}" > "${SSH_HOST_KEY_PATH}"
    - echo "${SSH_HOST_KEY_PUB}" > "${SSH_HOST_KEY_PUB_PATH}"

    - terraform init -input=false
    - ./run.sh

  after_script:
    - rm -rf ${HOME}/.ssh
    - rm -rf ${SSH_HOST_KEY_PATH}
    - rm -rf ${SSH_HOST_KEY_PUB_PATH}
