name: Renovate

on:
  schedule:
     - cron: "20 18 * * *" # every day at 9:00 AM UTC

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run Renovate
        uses: renovatebot/github-action@v44.2.1
        with:
          configurationFile: .github/renovate.json
        env:
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RENOVATE_REPOSITORIES: '["JunAr7112/gpu-driver-container"]'
          RENOVATE_ONBOARDING: false